stages:
  - verify
  - test
  - publish

check-format:
  stage: verify
  image: docker.io/node:24.18-trixie
  before_script:
    - npm install --global prettier@3.9.6
  script:
    - npx prettier --check .

build:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.14-trixie
  before_script:
    - uv sync --locked
  script:
    - make build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

publish:
  stage: publish
  image: ghcr.io/astral-sh/uv:python3.14-trixie
  before_script:
    - uv sync --locked
  script:
    - make build
  pages:
    publish: site
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
