stages:
  - test
  - publish

build:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.14-trixie
  before_script:
    - uv sync --locked
  script:
    - make build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

publish:
  stage: publish
  image: ghcr.io/astral-sh/uv:python3.14-trixie
  pages:
    publish: site
  before_script:
    - uv sync --locked
  script:
    - make build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
