site_name: Social Maps Documentation
site_url: https://docs.socialmaps.org/
repo_url: https://gitlab.com/socialmaps/docs
use_directory_urls: true
nav:
  - "index.md"
  - "ratings.md"
  - "lookups.md"
  - "API Reference": "/api/"
  - "SDK for Android": "/sdk/android/"
theme:
  name: material
  features:
    - content.footnote.tooltips
    - content.code.annotate
    - content.code.copy
plugins:
  - charts
  - search
extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5.33.0
  - https://cdn.jsdelivr.net/npm/vega-lite@5.23.0
  - https://cdn.jsdelivr.net/npm/vega-embed@6.29.0
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
  - js/katex.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
markdown_extensions:
  - footnotes
  - pymdownx.magiclink
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
