# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-09-15

openapi: 3.1.0
info:
  title: Social Maps API
  summary: A free & open API for reviewing Points of Interest (POIs), complementing OpenStreetMap.
  contact:
    name: Bora M. Alper
    email: bora@boramalper.org
  version: 0.1.0
paths:
  /users/{user_id}:
    get:
      tags:
        - Users
      summary: Retrieve a User
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/User/properties/id"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Bad Request. The provided `user_id` has an invalid format.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                InvalidUserID:
                  summary: 'user ID is invalid'
                  value:
                    message: 'Invalid `user_id`. User IDs start with `usr_` prefix.'
                    code: null
        '404':
          description: Not Found. No User with the provided `user_id` is found.
  /places/find:
    get:
      tags:
        - Places
      summary: Find a Place
      description: Find a Place by its location and name.
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
            example: "Cork Opera House"
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: double
            example: 51.9003921
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: double
            example: -8.4728019
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '400':
          description: Bad Request. Sent when the provided `user_id` has an invalid format.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                InvalidUserID:
                  summary: 'user ID is invalid'
                  value:
                    message: 'Invalid `user_id`. User IDs start with `usr_` prefix.'
                    code: null
        '404':
          description: Not Found. No Place with the provided details is found.
  /places/{place_id}:
    get:
      tags:
        - Places
      summary: Retrieve a Place
      parameters:
        - name: place_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Place/properties/id'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '404':
          description: Not Found
        '422':
          description: Validation Error
  /places/{place_id}/reviews:
    get:
      tags:
        - Reviews
      summary: List Reviews of a Place
      parameters:
        - name: place_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Place/properties/id'
        - name: order
          in: query
          schema:
            type: string
            enum: ['most_recent', 'most_helpful']
            default: 'most_recent'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: 'list'
                  data:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/Review'
                        - type: object
                          properties:
                            user:
                              $ref: '#/components/schemas/User'
        '404':
          description: Not Found
        '422':
          description: Validation Error
    post:
      tags:
        - Reviews
      summary: Post a Review of a Place
      security:
        - HTTPBearer: []
      parameters:
        - name: place_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Place/properties/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '202':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
        '422':
          description: Validation Error
  /reviews/{review_id}:
    get:
      tags:
        - Reviews
      summary: Retrieve a Review
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Review'
                  - type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                  - type: object
                    properties:
                      place:
                        $ref: '#/components/schemas/Place'
        '404':
          description: Not Found
        '422':
          description: Validation Error
    put:
      tags:
        - Reviews
      summary: Update a Review
      security:
        - HTTPBearer: []
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
        '422':
          description: Validation Error
    delete:
      tags:
        - Reviews
      summary: Delete a Review
      security:
        - HTTPBearer: []
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
      responses:
        '204':
          description: Successful Response (No Content)
        '404':
          description: Not Found Error
        '422':
          description: Validation Error
  /reviews/{review_id}/mark_helpful:
    put:
      tags:
        - Reviews
      summary: Mark a Review as helpful
      security:
        - HTTPBearer: []
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
        '422':
          description: Validation Error
  /reviews/{review_id}/unmark_helpful:
    put:
      tags:
        - Reviews
      summary: Remove helpful marking on a Review
      security:
        - HTTPBearer: []
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
        '422':
          description: Validation Error
  /reviews/{review_id}/flag:
    put:
      tags:
        - Reviews
      summary: Flag a Review
      description: |
        Flag a Review for moderator consideration, to report a potential breach
        of rules.

        Because there isn't a way to undo, clients MUST ask the user for
        confirmation before flagging a Review.
      security:
        - HTTPBearer: []
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
        '422':
          description: Validation Error
components:
  schemas:
    Place:
      type: object
      properties:
        object:
          type: string
          const: 'place'
          readOnly: true
        id:
          description: Unique ID of this Place.
          type: string
          pattern: '^plc_[a-zA-Z0-9]+$'
        name:
          description: Name of this Place.
          type: string
        location:
          description: |
            Geographic coordinates of this Place using the standard WGS84 projection.

            While storing and processing coordinates, do not use IEEE 32-bit floating point data type since it is limited to about 5 decimal places for the highest longitude whereas we use 7 decimal places.
          type: object
          properties:
            lat:
              description: Latitude coordinate in degrees (North of equator is positive).
              type: number
              format: double
              minimum: -90
              maximum: 90
            lon:
              description: Longitude coordinate in degrees (East of Greenwich is positive).
              type: number
              format: double
              minimum: -180
              maximum: 180
        review_stats:
          description: Statistics about the reviews users wrote about this Place.
          type: object
          properties:
            count:
              description: Number of reviews written.
              type: integer
              minimum: 0
            like_ratio:
              description: Ratio of reviews which liked this Place to all reviews.
              type: number
              minimum: 0
              maximum: 1
            rank:
              description: A measure of how much liked this Place is (higher is better), factoring in the recency of its reviews and the total number of reviews. We assume that reviews lose their relevance over time and more reviews give us greater confidence the likeability of a Place.
              type: number
              minimum: 0
              maximum: 1
      example:
        id: 'plc_nReHKJVfxZbhxmvi36r4rQ'
        name: 'Cork Opera House'
        location:
          lat: 51.9002419
          lon: -8.4730753
          review_stats:
            count: 2317
            like_ratio: 0.9297861
            rank: 0.9176327
    Review:
      type: object
      properties:
        object:
          type: string
          const: 'review'
          readOnly: true
        id:
          type: string
          description: Unique ID of this Review.
          pattern: '^rvw_[a-zA-Z0-9]+$'
          example: 'rvw_nReHKJVfxZbhxmvi36r4rQ'
          readOnly: true
        created:
          type: string
          description: Timestamp of when this Review was created.
          format: date-time
          readOnly: true
        place:
          description: The Place that the `user` is reviewing. Expandable.
          type: object
          properties:
            id:
              $ref: '#/components/schemas/Place/properties/id'
          readOnly: true
        user:
          type: object
          description: The User who authored this Review. Expandable.
          properties:
            id:
              $ref: '#/components/schemas/User/properties/id'
          readOnly: true
        liked:
          type: boolean
          description: Whether the `user` who authored this Review liked the `place`.
        comment:
          description: "`user`'s comments about the `place`, if any."
          oneOf:
            - type: string
            - type: 'null'
        marked_helpful:
          type: boolean
          description: Whether the user who is making the API call marked this Review as helpful before.
        helpful_stats:
          type: object
          description: Statistics about the helpfulness of this Review as indicated by other users.
          properties:
            count:
              type: integer
              description: Number of users who found this Review helpful.
              minimum: 0
            score:
              type: number
              description: A measure of how helpful this Review is, factoring in its recency (higher is better). We assume that Reviews lose their relevance over time and become less helpful.
              minimum: 0
          readOnly: true
      required:
        - id
    User:
      type: object
      properties:
        object:
          type: string
          const: 'user'
          readOnly: true
        id:
          description: Unique ID of this User.
          type: string
          pattern: '^usr_[a-zA-Z0-9]+$'
          example: 'usr_nReHKJVfxZbhxmvi36r4rQ'
        name:
          description: Name of this User, which can be their real name or nickname and does not have to be unique.
          type: string
      required:
        - id
    Error:
      type: object
      properties:
        message:
          description: A human-readable message in English providing more details about the error. You should not show these messages to your users.
          type: string
        code:
          description: For exceptions that are not programmer errors and that you can handle programmatically, an enum indicating what the issue is.
          oneOf:
            - type: string
            - type: 'null'

  securitySchemes:
    oAuthSample:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        authorizationCode:
          x-usePkce: true
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            write_reviews: Create, update, and delete your reviews on your behalf.
  responses:
    BadRequest:
      description: Bad Request. Typically due to malformed request syntax or invalid request body.
    
tags:
  - name: Places
    description: A **Place** is a Point of Interest (POI) in the world, such as a museum, a cafe, or a park.
  - name: Reviews
    description: A **Review** is a subjective assessment of a Place for the information of other users.
  - name: Users
    description: A **User** is a person who visits Places and reads & writes Reviews of them.
